w3c/web-roadmaps

index.html, js/generate.js
I was getting lots of mixed content warnings.
=> Changed W3C resource links to HTTPS

index.html
Links to categories in first menu were linking to nothing.
=> Added missing IDs to category sections

data/mediacontroller.json, index.html, specs/tr.json
MediaController and Web Audio API also added to Synchronized Content.
I did not attempt to write actual text for MediaController in particular, I
just added it to the right buckets.
=> Added MediaController, Timing Object, Web Audio API and NSD to Media Control

data/webaudio.json, specs/impl.json, specs/tr.json, tools/extract-impl-data.py
This PR is meant to replace PR #10 to add Webkit status for the Web Audio API. It fixes missing quotes in the other PR, and fixes the Python script that updates implementation status.
=> Add webkit status for Web Audio API and fix impl status generation

style.css
=> Tweak the style

data/media-capabilities.json, data/media-playback-quality.json, data/picture-in-picture.json, data/secondscreen-openscreen.json, data/ttml-imsc1.json, data/ttml1.json, media/capture.html, media/control.html, media/processing.html, media/rendering.html, media/synchronized.html, media/transmission.html, specs/impl.json, specs/tr.json
Updates to the media roadmap to add missing work items and drop those who are no longer worked upon.
=> Media roadmap updates

mobile/mediartc.html
The update splits content across well-deployed/work in progress/... sections and refreshes it with up-to-date information.
=> Update Media/RTC section of mobile roadmap

js/generate-index.js, js/generate.js
Indentation also used a mix of tabulations and spaces. Moved back to 2 spaces everywhere.
Also, there was a minor issue with the selector of header content that made it duplicate links in the header if there were such links.
=> Reformat JS files to use more modern array constructs

mobile/adaptation.html
The spec is CR, and all major browsers support these units.
=> Move viewport-percentage lengths to well-deployed technologies

data/fileapi.json, data/filereader.json, data/webstorage.json, mobile/storage.html, specs/impl.json, specs/tr.json
Implementation data refreshed as well.
=> Update storage section of mobile roadmap

data/beacon.json, data/cors.json, data/eventsource.json, data/fetch.json, data/online.json, data/picture-in-picture.json, data/websockets.json, data/xhr.json, js/generate.js, mobile/media.html, mobile/network.html, mobile/toc.json, specs/impl.json, specs/tr.json
Also renamed the "Media and RTC" section into "Media only", and the "Network integration" section into "Network and Communications".
=> Update network section of mobile roadmap

data/speech-api-recognition.json, data/speech-api-synthesis.json, mobile/userinput.html, specs/impl.json
As described in #50, speech synthesis is already well deployed across browsers while speech recognition is still underway, making it useful to distinguish the two when talking about the Speech API.
=> Distinguish speech synthesis from speech recognition

data/intersectionobserver.json, data/longtasks.json, data/paint-timing.json, mobile/performance.html, specs/impl.json, specs/tr.json
These 3 specifications have recently been published as First Public Working Draft. The First Paint specification was also moved from the WICG to the Web Performance Working Group, so I upgraded it to the "in progress" section.
=> Update info for First Paint, Long Tasks, and Intersection Observer

data/color-gamut.json, data/picture-in-picture.json
=> Fixed nits

publishing/media_overlay.html
Indended to replace pull request #97, which has probably been prepared against the `gh-pages` and not against the `master` branch.
=> [Publishing] Added more Media Overlay dependencies

publishing/media_overlay.html
(A minor bug in the previous update.)
=> Added a reference to MAUR

mobile/security.html
The data file is `data/sri.json`.
=> Fix the featureid of Subresource Integrity

js/generate.js
The framework was only considering `data-featureid` attributes that appared within a `data-feature` container. But roadmaps may reference feature IDs without any `data-feature`.
That's a typical need in "Discontinued features" sections and other sections for which no table needs to be generated at the end of the section.
This fixes #66.
=> [Framework] Auto-link featureid refs regardless of where they appear

js/generate.js
To guarantee consistency of section titles across pages and avoid duplicating efforts for translations, the framework now automatically sets the title of sections when the title is missing and when the section is a "well-known" one.
Well-known sections for now are those that have one of the following classes:
- well-deployed
- in-progress
- exploratory-work
- not-covered
- discontinued
Translations of these section titles may be provided in a `sections` property of the `translations.xx.json`, using the above class names as keys and translated titles as values.
This update addresses issue #69.
NB: I haven't updated existing pages to drop titles as part of this commit. To be done later on.
=> [Framework] Add titles to well-known section types when not already set

assets/css/roadmap.css
The updated styles allow to add an `<h2>` header with the date and/or type of the document, as well as a `<details>` section with information about the document (link to latest version, link to this version, etc.)
=> [Framework] Adjust styles for date and version information

mobile/adaptation.html, mobile/forms.html, mobile/graphics.html, mobile/index.html, mobile/lifecycle.html, mobile/media.html, mobile/network.html, mobile/payment.html, mobile/performance.html, mobile/security.html, mobile/sensors.html, mobile/storage.html, mobile/userinput.html
Document metadata section completed with:
- a link to the Editor's draft
- links to the repository
Note this will look better once PR #144 that updates the styles will have been merged.
=> Complete document metadata and add date to individual pages

mobile/storage.html
=> [Mobile] Add missing data-feature attribute to "download" feature

mobile/sensors.html
=> [mobile] Mention Motion Sensors Explainer

media/synchronized.html
I have added media-synchronised Web animations to the "Features not covered by ongoing work" section under "Media orchestration".
=> [media] Added media-synchronised web animations

data/element-queries.json, mobile/adaptation.html
See #174. I used both "element queries" and "container queries" because both terms seem to be used to describe the feature.
=> [Mobile] Mention element queries in device adaptation

data/css-font-display.json, data/css-font-loading.json, mobile/graphics.html
This includes:
* Adding `font-display`;
* Adding `edgestatus` for `css-font-loading`.
=> [mobile] Refine the downloadable fonts feature

js/template-about.html
For example:
* https://en.wikipedia.org/wiki/360_Secure_Browser
* https://zh.wikipedia.org/wiki/QQ%E6%B5%8F%E8%A7%88%E5%99%A8
* https://zh.wikipedia.org/wiki/%E6%90%9C%E7%8B%97%E9%AB%98%E9%80%9F%E7%80%8F%E8%A6%BD%E5%99%A8
=> A browser can be based on multiple browser engines

mobile/about.html, mobile/forms.html
The feature itself is stable and supported by various browsers... although only to some extent. The text makes it clear that implementations may be partial.
=> [Mobile] Move date and time from entries to well-deployed section

mobile/about.html
=> [mobile] Update Change History

js/generate-utils.js
Thanks @xueyuanjia for pointing this out!
=> [Framework] Typo fix

mobile/storage.html, mobile/storage.zh.html
=> [mobile] Mention Indexed Database API 3.0

data/priority-hints.json, mobile/performance.html
=> [mobile] Mention Priority Hints

data/gamepad.json, mobile/userinput.html
=> [mobile] Mention Gamepad

data/referrer-policy.json, mobile/security.html
=> [mobile] Mention Referrer Policy

data/mst-content-hint.json, mobile/media.html
=> [mobile] Mention MediaStreamTrack Content hints

data/css-contain.json, mobile/graphics.html, mobile/performance.html
Also move css-will-change to performance.html.
Fix #276 and #290.
=> Mention css-contain; add intro text to graphics.html

mobile/userinput.html
The mention links to the Gesture events proposal. No data file created for now because that still seems very early stages.
Fix #261
=> [Mobile] Mention Gesture events in User Interaction

mobile/graphics.html, mobile/sensors.html
=> [mobile] Move Screen Orientation API to a more appropriate place

data/budget-api.json, mobile/lifecycle.html
=> [Mobile] Mention Web Budget API in Application Lifecycle

data/animation-worklet.json, mobile/performance.html
=> [mobile] Mention CSS Animation Worklet API

data/geolocation-sensor.json, mobile/sensors.html, mobile/sensors.zh.html
Also:
- Update the data
- Tweak the Chinese translation
=> Move Geolocation Sensor to "Technologies in progress"

js/translations.zh.json, media/rendering.html, mobile/media.html
Ref: https://github.com/WICG/picture-in-picture/pull/33
=> s/Picture in Picture/Picture-in-Picture/g

mobile/userinput.html
Split the text that was in technologies in progress into two parts:
- Pointer Events to well-deployed technologies
- Input Device Capabilities to Exploratory work
Fix #333
=> [Mobile] Move Pointer Events to Well-deployed technologies

mobile/lifecycle.html
The proposal was dropped for lack of adoption and concerns over the design of a solution in this space.
Fix #309
=> [Mobile] Move Budget API to Discontinued features section

data/event-timing.json
=> [data] Update URL and title of Event Timing API

data/scroll-animations.json, mobile/graphics.html
=> [mobile] Mention Scroll-linked Animations

data/css-paint-api.json, mobile/graphics.html
=> [mobile] Mention CSS Painting API

games/lifecycle.html, mobile/sensors.html
=> [mobile] Mention background operations of geolocation-sensor

data/portals.json, mobile/lifecycle.html
Adds Portals to application lifecycle, borrowing text from the discussions on [Discourse](https://discourse.wicg.io/t/proposal-for-promotable-iframe/2375) and from the [explainer](https://github.com/WICG/portals/blob/master/explainer.md)
Fix #327
=> [Mobile] Mention Portals

data/display-locking.json, mobile/performance.html
Mentioned in Performance and Tuning, borrowing text from the explainer:
https://github.com/WICG/display-locking/blob/master/explainer.md
Fix #329
=> [Mobile] Mention Display Locking

data/webhid.json, mobile/userinput.html
Mentioned in User interaction under exploratory work.
Fix #330.
=> [Mobile] Mention WebHID

mobile/about.html
Change history since publication of the July 2018 snapshot.
The URL of the December 2018 snapshot does not exist yet.
The Pull Request should only be merged once other pending pull requests have been merged.
=> [Mobile] Create change history for December 2018 snapshot

data/native-file-system.json, data/writable-files.json, js/translations.zh.json, mobile/storage.html, mobile/storage.zh.html
Ref: https://github.com/WICG/native-file-system/commit/4d25eefd75bb8eda5a9ad46c4977e7180ac57fcc
=> Rename Writable Files to Native File System

data/element-queries.json, data/resize-observer.json, mobile/adaptation.html, mobile/adaptation.zh.html
=> [mobile] Mention Resize Observer

data/trusted-types.json, mobile/security.html
=> [mobile] Mention Trusted Types

mobile/adaptation.html
=> [mobile] Move CSS Mobile Text Size to In progress section

data/css-overscroll-behavior.json, mobile/performance.html
=> [mobile] Move overscroll-behavior to In progress section

data/kv-storage.json, mobile/storage.html
The text mentions the plan to merge the spec into IndexedDB after a period of incubation.
Fixes #366.
=> [Mobile] Mention KV Storage in Data Storage

data/js-self-profiling.json, mobile/performance.html
=> [Mobile] Mention JS Self-Profiling API

mobile/sensors.html
=> [Mobile] Update description of DeviceOrientation Event

data/cookie-store.json, mobile/storage.html
=> [Mobile] Mention Cookie Store API

data/feature-policy.json, mobile/security.html, mobile/security.zh.html
The spec has been adopted by the Web Application Security Working Group and published as a FPWD.
=> [mobile] Move Feature Policy to technologies in progress

mobile/security.html
=> [mobile] Move Hadware Based Security Services to discontinued section

mobile/about.html, mobile/about.zh.html
Draft changelog for the April 2019 release. Should only be merged when we're ready to publish.
=> [mobile] Add changelog for April 2019 release

data/animation-worklet.json, mobile/performance.html, mobile/performance.zh.html
And move it to Technologies in progress.
=> Update the URL for CSS Animation Worklet API

data/is-input-pending.json, mobile/performance.html, mobile/userinput.html
=> [mobile] Mention isInputPending

data/element-timing.json, data/layout-instability.json, data/timing-entrytypes-registry.json, mobile/performance.html
Fixes #409.
Fixes #410.
Fixes #411.
=> [mobile] Mention new performance metric interfaces

data/virtual-scroller.json, mobile/performance.html
=> [mobile] Mention virtual-scroller proposal

data/audio-device-client.json, mobile/media.html
=> [mobile] Mention Audio Device Client

data/css-scoping.json, data/css-shadow-parts.json, data/dom.json, data/html.json, mobile/adaptation.html
=> [mobile] Mention Web components

data/web-transport.json, mobile/network.html
=> [mobile] Mention WebTransport

mobile/performance.html
=> [mobile] Move css-contain-1 to Well-deployed

data/webrtc-svc.json, mobile/media.html
=> [mobile] Mention webrtc-svc

data/webxr-ar-module.json, data/webxr-gamepads-module.json, data/webxr.json, mobile/media.html
=> [mobile] Mention WebXR modules

data/hr-time.json
=> [data] Use level 2 shortname for High Resolution Time

mobile/about.html
I'll add the Chinese translation after this PR is merged.
=> [mobile] Add changelog for November 2019 release

data/web-share.json, mobile/lifecycle.html, mobile/lifecycle.zh.html
And move it to Technologies in progress.
=> Update the URL for Web Share API

data/trusted-types.json, mobile/security.html, mobile/security.zh.html
Add link to polyfill and move it to Technologies in progress.
=> Update the URL of Trusted Types

data/webgpu.json, data/wgsl.json, mobile/graphics.html, mobile/graphics.zh.html
Also mentions the companion WebGPU Shading Language specification.
@xfq The Chinese translation obviously needs a bit of additional love :-)
=> Move WebGPU to technologies in progress in Graphics

data/construct-stylesheets.json, mobile/adaptation.html
=> Mention Constructable Stylesheet Objects

data/performance-measure-memory.json, mobile/performance.html
=> Mention performance.measureMemory API

data/secondscreen-openscreen.json, mobile/media.html
=> Move Open Screen Protocol to Technologies in progress

data/main-thread-scheduling.json, data/request-post-animation-frame.json, mobile/performance.html
- Mention Main Thread Scheduling proposals (fix #488)
- Mention requestPostAnimationFrame proposal (fix #491)
=> [mobile] Update Performance page

data/web-monetization.json, mobile/payment.html
=> [Mobile] Mention Web Monetization in Payment and Services page
