w3c/web-roadmaps

- js/generate.js
This commit ensures that browsers we're not interested in get filtered out from the implementation data right away.
The "Current Implementations" column details the implementation status in main browsers. Implementation data may contain information about other browsers though (e.g. Firefox for Android, Safari for iOS, Opera Mini). That information is filtered out and not rendered for the time being. However, the code still took that information into account to decide whether to render the section's title.
In other words, the code could generate an empty "Shipped" or "In development" implementation section.
> Ensure impl section titles only appear when list is not empty

- data/storage.json
- mobile/storage.html
The Quota Management API has been discontinued in favor of the Storage spec.
> Replace Quota Management API by Storage spec

- data/intersectionobserver.json
- mobile/performance.html
- specs/impl.json
The Intersection Observer specification makes it possible to implement infinite scrolling lists efficiently, which is particularly relevant on mobile devices.
> [mobile] Add Intersection Observer to performance section

- data/css-2d.json
- data/css-3d.json
- data/css-border-background.json
- data/css-border-radius.json
- data/css-border-shadow.json
- data/css-border.json
- mobile/graphics.html
- specs/impl.json
- specs/tr.json
Main changes:
- start section with CSS, since that's the core technology here
- adjusted references to CSS Borders and Background specs
- added references to Can I Use for some of the missing specs (probably need to be completed with IDs from other platform status sites, not done for now)
- moved requestAnimationFrame, CSS Flexbox, CSS Animations and CSS Transitions to well-deployed section
- re-indented content
> [mobile] Second pass on the Graphics section

- data/inputdate.json
- data/inputmode.json
- data/inputtext.json
- mobile/forms.html
Main changes:
- moved date and time input types and inputmode attribute to "in progress" section given the lack of implementation support for now.
- noted the uncertain future of the "inputmode" attribute, which may be removed from HTML due to lack of implementations
- renamed features as needed
- removed use of bold around feature names
- re-indented content
> [mobile] Second pass at Forms section

- publishing/index.html
> Unify the title of the publishing roadmap

- data/html-media-capture.json
- data/inputaccept.json
- media/capture.html
- mobile/media.html
Also renamed the data file to use the TR shortname.
Note the explicit mention of available implementations since the framework does not report on implementations in mobile browsers for now.
Addresses #86.
> [Media] Add HTML Media Capture

- data/css-border-background.json
- data/css-border-radius.json
- data/css-border-shadow.json
The old URL seems to be removed from `tr.rdf`.
> Update the URL of CSS Backgrounds and Borders Module Level 3

- js/generate-index.js
- js/generate.js
This commit implements the following changes:
- Custom directives in the <head> are now preserved. This makes it possible to set a different <base> but also to override the CSS as well as to insert JS code if needed (fixes #76)
- Given an empty <a data-featureid="[feature]"></a>, the code automatically sets the content of the link to the name of the feature if it exists, in other words the "feature" value in the "data/[feature].json" file, or to the title of the underlying specification otherwise (fixes #78)
- IDs are automatically generated for sections, feature paragraphs and individual feature references. The code used was stolen from Respec (fixes #95)
> Generate IDs, auto-expand feature names, preserve custom directives

- data/geolocation-sensor.json
- mobile/sensors.html
This spec recasts the Geolocation API on top of the Generic Sensor API.
> [mobile] Add Geolocation Sensor

- tools/extract-impl-data.py
Update the Python code that computes the implementation status of each feature to also expose the implementation data and sources used to compute the final status in an "implementations" property. That information is not used for the time being, but could typically be used later on to complete the information in the implementation column of generated tables.
The rules used to compute the implementation status have also been refined not to end up in situations where we claim that a feature has shipped in Safari and is still in development in Webkit (as reported in #87).
The rules are the following (rules appear as code comments too):
1. Trust platform sources to say the right thing about their own user-agent or rendering engine. For instance, if chromestatus says that a feature is "in …
> [Framework] Expose impl sources and complete impl status rules

- assets/css/roadmap.css
- js/generate-index.js
- js/generate.js
The side menu now displays icons. The same grey filter as the one applied to home page icons on narrow screens is applied to icons in the side navigation menu so that the menu remains "gentle to the eye".
Also, the menu hamburger is now automatically hidden in pages when there are no other pages in the roadmap.
Fixes #71.
> Add icons to navigation menu

- README.md
- js/generate.js
- js/translations.json
- js/translations.zh.json
* Moved English labels that were hardcoded in the code to a separate `js/translations.json` file, to improve symmetry between languages.
* Within translations files, moved implementation status labels to a separate `implstatus` property, so that `labels` only contains real labels.
* Renamed `groupnames` and `spectitles` properties into `groups` and `specifications` to avoid having to think about whether to use camel case, and improve consistency with other property names.
* Improved localization warnings reported to the console, to avoid duplicates in particular
* Implemented an ad-hoc mechanism to deal with the "in" label, which is now "%feature in %spec". This should (hopefully) be enough for now.
* Completed the translation instructions in the README, to explain which files need to be …
> [Framework] Improve i18n code (mostly "editorial" updates)

- README.md
- assets/css/theme.css
- data/intersectionobserver.json
- data/ttml-imsc1.json
- js/generate.js
- tools/extract-impl-data.py
The implementation status can now be specified in the data/ file that describes a feature, in an `other` property of an `impl` property. That property should take an object that sets the additional implementation status per user agent.
For instance:
```json
{
"impl": {
"other": {
"safari": "shipped",
"chrome": "indevelopment",
"firefox": "experimental"
}
}
}
```
Alternatively (but not necessarily encouraged for now as long as information remains simple), the property can take an array of implementation info as in:
```json
{
"impl": {
"other": [
{ "ua": "safari", "status": "indevelopment", "source": "rumors" },
{ "ua": "edge", "status": "experimental", "source": "dreams" }
]
}
}
```
This implementation info completes the implementation info gathered automatically in `spec/impl.json`. …
> [Framework] Impl and polyfills can now be listed in data/ files

- README.md
- assets/img/home.svg
- js/generate.js
Adds a "Home" like to the navigation menu on multi-page roadmaps. The link is made back to `index.xx.html` when the lang is not English.
The icon is home made and so-so... but hey, I did what I could!
This PR addresses issue #70.
> [Framework] Automatically add a "Home" link to side menu

- media/control.html
- media/toc.json
The new name clarifies that the section is about user interaction to control media playback, not about controlling the media settings such as the codec, bitrate, etc.
Addresses issue #125.
> [Media] Rename "Media control" section into "Playback controls"

- data/css-border-background.json
The reference was to CSS border radius, which was incorrect. There are no entries for the CSS Background and Borders spec as such on any of the status platforms.
There are entries for individual properties of the CSS Backgrounds and Borders spec in Can I Use, but we still do not have a proper way to reference them here:
- background-attachment
- css-backgroundblendmode
- css-background-offsets
- background-repeat-round-space
Fixes #132.
> [Data] Drop ref to "Can I Use" for CSS Backgrounds and Borders

- data/geofencing.json
- data/task-scheduler.json
- mobile/lifecycle.html
The first spec was developed by the SysApp Working Group.
The second spec was developed by the Geolocation Working Group.
Both specs have been retired, but are referenced as discontinued features in the Lifecycle section of the mobile roadmap.
This fixes #133.
> [Data] Add Task Scheduler and Geofencing specs

- data/web-lifecycle.json
- mobile/lifecycle.html
The Web Lifecycle proposal is now being incubated in the WICG.
This fixes #146.
> [Mobile] Move Web Lifecycle proposal to Exploratory Work

- js/generate.js
The code was explicitly not referencing any icon for notes, but a Note maturity is now available:
https://www.w3.org/2013/09/wpd-rectrack-icons/note.svg
The update partially relates to #111 (as the "Note" icon was missing too)
> [Framework] Drop specific maturity icon rule for Note documents

- js/filter-implstatus.js
- js/generate.js
- js/utils.js
The new `filter-implstatus.js` script runs once a page has been generated (either dynamically or statically if the current page is a published export), and filters the list of user agents that appear in "Current implementations" columns in generated tables based on the presence of a "ua" query string parameter.
The script expects the query string parameter to contain a comma-separated list of the user-agents that need to appear. For instance:
- `ua=firefox` to only display the current implementation status in Firefox
- `ua=chrome,edge` to display the current implementation status in Chrome and in Edge.
The script also updates navigation links to preserve the query string across pages.
This update addresses issue #143, although note the filtering would benefit from further enhancements in …
> Filter UA in implementation status column based on query string param

- data/payment-method-id.json
- data/payment-method-manifest.json
- data/payment-request.json
- mobile/payment.html
The First Public Working Draft of the Payment Method Manifest specification was published early December 2017, and did not yet appear in the mobile roadmap, as raised in #157.
Also added the Payment Method Identifiers specification to provide a complete overview of payment technologies under development.
Payment spec data adjusted based on contents browser status platforms as well.
> [Mobile] Mention Payment Method Identifiers and Manifest specs

- data/web-share-target.json
- data/web-share.json
- mobile/lifecycle.html
See #75. Sharing content on mobile devices is a very common paradigm.
Listed in Lifecycle, because it is about integrating with the rest of the system to provide a native-like experience.
> [Mobile] Mention Web Share API and Web Share Target API

- data/epr.json
- data/permissions-request.json
- data/permissions-revoke.json
- data/permissions.json
- mobile/security.html
See #170.
Note that the Chrome status platform currently combines the two specs into one entry (entry which incorrectly links to the Permissions spec). I kept the specs separate on our side.
This update also:
- adds the missing "epr" data file (for the discontinued "Entry Point Regulation" spec mentioned at the end of the page)
- fixes a missing "data-feature" for the Permissions spec
- adds a Chrome status entry for the Permissions spec
> [Mobile] Mention Requesting/Revoking permissions specs

- data/secondscreen.json
- tools/extract-impl-data.py
See #173. The Chrome status platform incorrectly reports that the Presentation API is in development in Safari. This is a priori wrong. This update forces the Webkit implementation status to `""`, meaning to "not implemented".
Note the Python code that computed the Webkit status ignored the empty string when it bumped into one. It now makes a difference between `""` (which means "not implemented"), and `None` (which means "no info").
> [Data] Force Webkit status for Presentation API

- data/barometer.json
- data/thermometer.json
- mobile/sensors.html
See #159. The roadmap mentioned the Ambient Humidity Events spec in the Exploratory Work section but work has been discontinued. This update moves that spec to the Discontinued feature section, and completes the note to mention the Thermometer and Barometer proposals. Work on these proposals may resume any time if there is enough implementer support.
> [Mobile] Mark humidity, thermometer, barometer proposals as discontinued

- mobile/performance.html
Cooperative Scheduling of Background Tasks is a Proposed Recommendation now, and shipped with Chrome and Firefox.
Should we move it to well-deployed now?
> [mobile] Move requestIdleCallback to well-deployed

- README.md
- data/ambientlight.json
- data/secondscreen.json
- tools/extract-impl-data.py
See #160. I completed the implementation algorithm to consider that a "feedback" source is authoritative. I also added a comment and a date to the feedback information in the data folder to ease maintenance over time. The Python code passes that information over to the JavaScript, which does not do anything with it for the time being.
> Fix Ambient light API implementation status in Firefox and Edge

- data/animation-frames.json
- data/audio.json
- data/autocomplete.json
- data/datalist.json
- data/html5-download.json
- data/htmlmediaelement.json
- data/inputdate.json
- data/inputhint.json
- data/inputpattern.json
- data/inputtext.json
- data/online.json
- data/picture.json
- data/srcset.json
- data/timeupdate.json
- data/video.json
- mobile/forms.html
- mobile/storage.html
`appcache.json` and `inputmode.json` were not updated, because the relevant spec sections were removed in HTML 5.2.
> [mobile] Update the links to HTML 5.2

- data/proximity.json
See #160 and previous update to the Ambient Light sensor implementation status. The version that ships in Firefox is not the latest version of the spec, which is based on the Generic Sensor API.
> [Mobile] Fix proximity sensor implementation status

- mobile/lifecycle.html
See #191. While still widely supported, the application cache mechanism was obsoleted in HTML 5.1 and dropped from HTML 5.2.
> [Mobile] Move appcache to the discontinued features section

- data/streams.json
- mobile/network.html
See #162. Streams have some practical benefits in mobile devices as they allow more fine-grained control over network usage. Also they may be used to improve perceived rendering performances, as described in:
https://jakearchibald.com/2016/streams-ftw/
Note: Streams are mentioned on Webkit status and Edge status platforms, but at a more fine-grained feature level, which we don't yet support.
> [Mobile] Mention streams in Network

- data/webvr.json
- data/webxr.json
- mobile/media.html
See #188. I moved WebVR to the Discontinued features section since development on it halted, and pointed out that WebXR also addresses AR scenarios.
Also updated the WebVR CG name into the new "Immersive Web CG", even though they haven't enacted that change on the CG home page yet.
> [Mobile] Replace WebVR by WebXR in the media page

- data/atag20.json
- data/mobile-accessibility-mapping.json
- data/mwbp-wcag.json
- data/uaag20-reference.json
- data/uaag20.json
- data/wai-aria11.json
- mobile/toc.json
- mobile/userinput.html
See #184.
Some of the references were (still mostly valid but) outdated. The text was updated and is much more complete, mentioning the different guidelines (UAAG for user agents, WCAG for developers, ATAG for authoring tools), and highlighting mobile-oriented specificities when they exist.
The "User Input" section was also renamed into "User Interaction", which seems a better term to describe what the page is about. The page description mentions accessibility as well, and the page now starts with an introduction that explains the scope of the page.
> [Mobile] Update accessibility part in User input

- data/webxr.json
- media/rendering.html
See #188. WebXR Device API aims at replacing the WebVR specification.
Development of the WebVR spec has now halted.
@chrisn Can you review?
> [Media] Replace WebVR by WebXR

- README.md
- data/background-sync.json
- data/feature-policy.json
- data/geolocation-sensor.json
- data/inband.json
- data/inputdevice.json
- data/media-capabilities.json
- data/media-playback-quality.json
- data/mediasession.json
- data/mobile-wcag.json
- data/netinfo.json
- data/picture-in-picture.json
- data/shape-detection.json
- data/viewportapi.json
- data/web-share-target.json
- data/web-share.json
- data/webbluetooth.json
- data/webusb.json
- tools/extract-spec-data.js
Addresses #208.
The code now makes use of the `publisher` property returned by Specref to find a friendly label for the group that delivered the spec.
It also tries to set a `publisher` property, which is for now one of W3C, IETF or WHATWG. If that property is not already set, it looks at the URL of the group and at the URL of the spec to find out which organization published it.
Note I made a first pass at the data files to remove information that is no longer needed. Specref does not have all the specs we need to reference though (I'll try to prepare PR against Specref to add them)
> [Framework] Improve group info logic and expose publisher

- Makefile
- README.md
- compile.sh
- data/ambientlight.json
- data/proximity.json
- package.json
- tools/extract-impl-data.js
This update completes the implementation info retrieved from Web platform status
sources:
- a `prefix` flag is set when the implementation requires a prefix
- a `flag` flag is set when the implementation is behind some sort of flag
- status is set to `experimental` instead of `shipped` whenever the `prefix` or `flag` flags are set
- a `notes` array contains implementation notes when available (the `comment` property in the data file gets mapped to that array)
- mobile browser names normalized in a more logical way, now follow the names used in mdn-browser-compat (preliminary work for #13)
- better support for Chrome implementation info, in particular on Android (preliminary work for #13)
This info is not yet being used by the Web application, so the update does not change much for now, …
> [Framework] Complete impl info (prefix, flag, notes)

- assets/css/theme.css
- js/filter-implstatus.js
- js/generate-utils.js
- js/generate.js
- js/translations.json
- js/translations.zh.json
Follow-up to PR #216 to [keep dependencies minimal in published snapshots](https://github.com/w3c/web-roadmaps/pull/216#issuecomment-381513338).
The filtering menus of the implementation column are now generated by the `generate.js` script. This means that the `filter-implstatus.js` script:
1. stays agnostic about browsers that it needs to filter. The script merely uses the info in the filtering menus and does not need to hardcode a precise list of browsers.
2. no longer needs to load translation files, which thus do not need to be kept around in published snapshots.
The `generate-utils.js` and `utils.js` scripts have been kept separated for now to ease review but they can be merged again afterwards.
The update also adds the possibility to provide translations of "desktop" and "mobile" in …
> [Framework] Move filtering menus generation logic

- tools/extract-impl-data.js
The Chrome Platform Status data is forward-looking in the sense that features implemented in upcoming versions of the browser may be flagged as "shipped".
The data does not state which version is the "current" version. We take that info from Can I Use, and consider that the desktop and Android versions are always equal (they are usually released within 1-2 days of one another).
For Opera, the rule applied in the Chrome Platform Status data is that Opera vX is based on Chromium vX+13. That is true for Opera for Desktop and releases seem to be synchronized too, so the code assumes that the current version of Opera for Desktop is the current version of Chromium minus 13. That is not true for Opera for Android, and the data seems wrong here (see discussion in #13).
Actually Can I use data for …
> [Framework] Fix Chrome Platform parsing, drop Opera for Android

- assets/css/roadmap.css
- assets/css/theme.css
- js/generate-utils.js
- js/sidenav.js
- js/template-page.html
- js/template-page.zh.html
This update contains a short series to address main reported accessibility issues of the User Interface. Changes are:
- Links in text are underlined (#226)
- Menu is now keyboar accessible and "Tab/Up/Down/Home/End" key friendly (#227)
- Feature labels in tables are top-aligned when there the column spans multiple rows (#229)
- Menu button is correctly labelled (#230)
- Contrast of table headers improved (#231)
- Contrast of footer improved (#232)
Actually, the menu can now be opened and closed through the "m" key. I haven't tried to advertise that anywhere for now.
The update also fixes the URL of the about page in translations (#233)
@xfq I let you update the "alt" texts for the menu button in `template-page.zh.html`!
> [Framework] A series of UI accessibility improvements

- .gitignore
- README.md
- js/filter-implstatus.js
- js/generate-utils.js
- package.json
- tools/generate-roadmaps.js
This update adds a script that generates all roadmap pages to a `.out` folder and copies relevant assets there as well. Addresses #129 (and part of #228 in the sense that we'll be able to replace the `gh-pages` branch with the generated pages).
Under the hoods, the script uses JSDOM to load HTML pages, run the generation in individual pages, and save the generated HTML content.
Some bits of code were adjusted accordingly not to create absolute URLs for translation links, and to respond to the right "load" event in generated documents.
What would still need to be done to complete this update:
1. use that mechanism to create the `gh-pages` branch in the Travis CI script
2. stop producing `tr.json` and `impl.json` in the `specs` folder. They should now directly be generated in the `.out` …
> [Framework] Script to generate all roadmap pages automatically

- README.md
- js/generate-utils.js
- js/translations.zh.json
- media/toc.json
- mobile/toc.json
- publishing/toc.json
- security/toc.json
- web5g/toc.json
See #166. The framework will now automatically generate a Document Metadata section in the index page of a multi-page roadmap, with appropriate links. README updated to mention the different settings that may need to be added to the `toc.json` file, namely `publishedVersion`, 'edDraft, `thisVersion`, `previousVersion`, `github` and `publishDate`.
When specified, the `publishDate` appears next to the page's title in all pages. Other information only appear in the index page.
@xfq, note the need to add a few translations under a `metadata` properties in the translations file.
> [Framework] Auto-generate Document Metadata section

- assets/css/theme.css
- js/generate-utils.js
- mobile/about.html
Add a changes since previous published version to the About page that highlights the list of updates in different sections, and quickly explains other changes made to the UI and underlying framework.
This update also introduces a generic way to link to roadmap pages with a `data-page` attribute whose value must be the URL of the page as it appears in the `toc.json` file (without the extension). The framework updates these links automatically, targeting the localized version when needed.
I did not try to link to GitHub issues and pull requests because that seems too "techy" for casual readers. It could perhaps have been useful to provide more details as to why a particular feature was added but the link to the roadmap page should hopefully provide the incentive to read it!
Note the change …
> [Mobile] Add a changelog since previous snapshot

- js/generate-utils.js
- js/template-page.html
- js/template-page.zh.html
See #72. Two dates are being mentioned in the footer:
1. The date when the content iself was last updated. The assumption is that the last modified date of the document will be the correct date.
2. The date when the implementation data (and spec info) was last updated. The assumption is that this is the current date at the time when the page is generated.
As an exception to the rule, if `publishDate` is specified, then it is used (except for the content if it is more recent than `document.lastModified`)
The dates are not perfect. Also, having two dates is probably a bit confusing. But then both dates seem to make sense, and could be useful, especially on roadmap pages published on GitHub (e.g. to point out that content may be 6 months old, but implementation data is still "current").
@xfq …
> [Framework] Add last modified dates to footer

- js/generate-utils.js
Last modified dates and publication dates were always formatted in English. They should now be formatted according to the language of the page.
Under the hoods, the `toLocaleDateString` method gets used to format the date. Note browsers may only support a subset of locale settings in practice (and may for instance only support locale settings that are actually local to the user), so that mechanism may not always work.
In particular, JSDOM, used to generate all roadmap pages in batch, does not seem to support Chinese, so rules for Chinese are hardcoded if JSDOM is detected.
This commit is a fix for:
https://github.com/w3c/web-roadmaps/issues/213#issuecomment-386197580
> [Framework] Localize date strings in pages

- js/filter-implstatus.js
- js/generate-utils.js
Fix for #255
Also stick to `indexOf` instead of `includes` in case people are looking at the roadmap using IE (but keep `includes` in the generation logic since it should only run on modern user-agents)
> [Framework] Detect JSDOM in User-Agent string

- README.md
- js/generate-utils.js
- js/translations.json
- tools/extract-spec-data.js
- tools/spec.jsons
- tools/tr.jsons
Features initially proposed in https://github.com/w3c/web-roadmaps/issues/90.
W3C specs are automatically flagged as informative when they contain only informative content or when they will be (or have been) published as a Note.
Specs can also be flagged as "evergreen", which means that, regardless of their exact status on the Rec-track (or elsewhere), they can be considered fit for reference. This is roughly equivalent to the notion of a Living Standard in WHATWG. I did not create a new maturity status for this, because we might want to render the information separately later on.
These settings are used to adjust the maturity icon being rendered. Notably:
- regardless of their exact maturity status, evergreen specs use a green "REF" (for "Reference") icon.
- informative icons are in dark …
> [Framework] Custom maturity icons for evergreen/informative specs

- README.md
- assets/css/theme.css
- js/generate-utils.js
- js/translations.json
- js/translations.zh.json
- tools/extract-spec-data.js
- tools/spec.jsons
- tools/tr.jsons
The framework can now render a "See also" column that contains useful links to resources related to the specification, notably:
- a link to the Editor's Draft
- a link to the repository that contains the Editor's Draft
- specific links defined in the description of the spec.
The "See also" column is only rendered in the (currently unused) `versions` type of summary table. The exact links that need to be rendered can be customized in the `toc.json` file. The README explains how to customize the summary tables.
The `repository` property is either constructed from the URL of the Editor's Draft or retrieved from Specref.
See related need expressed in https://github.com/w3c/web-roadmaps/issues/90
NB: The framework more or less already supported a `versions` column but that wasn't flexible …
> [Framework] New "See also" column in summary tables

- README.md
- assets/css/theme.css
- js/generate-utils.js
- js/translations.json
- tools/extract-spec-data.js
- tools/spec.jsons
- tools/tr.jsons
Implements idea raised in https://github.com/w3c/web-roadmaps/issues/260
The new `milestones` column type renders known publication milestones for the underlying specification. Milestones are retrieved from the W3C Spec dashboard:
https://github.com/w3c/spec-dashboard/tree/gh-pages/pergroup
(files whose name ends with `-milestones.json`).
That columns should typically be added to the summary tables at the end of "Technologies in progress" sections. This column is not displayed by default for now because the milestone information available is still too scarce. Hopefully, this will change in the near future.
> [Framework] New "milestones" column in summary tables

- assets/css/roadmap.css
- js/generate-utils.js
- js/sidenav.js
- js/template-page.html
- js/template-page.zh.html
See https://github.com/w3c/web-roadmaps/issues/239
Navigation menu should still be functional when JS is not around. This update renders the menu by default towards the end of the page, allowing user to navigate even when JS is off.
When JS is off, navigation menu is not rendered on the home page because it would merely duplicate the content.
Ideally, the navigation menu would be rendered on the left of the page when screen is wide enough. Not done here because that would require a bit of code refactoring. Could be considered later on if that feels needed, but that does not seem to be a priority.
> [Framework] Make nav menu not dependent on JS

- README.md
- js/generate-utils.js
- package.json
- tools/create-missing-data.js
- tools/extract-spec-data.js
See https://github.com/w3c/web-roadmaps/issues/77.
The new `create-missing-data.js` tool, integrated in `npm run all` parses the roadmap pages and creates empty data files for specs that these pages reference (in `data-featureid` attributes) when that is needed.
Note that this mechanism will only work for W3C specs, where the reference is supposed to use the spec's shortname. Generation will break at the `generate-specinfo` step otherwise, because the framework won't be able to extract any information about the spec from the W3C API.
The created data files would obviously need to be added to the repository afterwards. This remains a manual step. In any case, this seems only useful when the data file gets completed with implementation info.
Updates to the other scripts in this pull request …
> [Framework] New tool to create missing data files for W3C specs

- README.md
- js/generate-utils.js
- js/generate.js
See https://github.com/w3c/web-roadmaps/issues/106
3 new mechanisms to link to the Editor's Draft:
1. add a `data-linkto="ED"` attribute next to the `data-featureid` attribute to have the framework link to the Editor's Draft for that link
2. add a `linkto` property set to `ED` to the `toc.json` file to have the framework link to the Editor's Draft for all links in the prose.
3. define custom tables and set the `linkto` property of the `spec` column to `ED` to tell the framework to link to the Editor's Draft in the summary table.
Note the update also fixes fragment handling when features are targeted (the URL of the feature was previously unused, meaning links always targeted the top of the spec, and not the relevant section when a feature was used).
> [Framework] Add mechanism to link to the ED

- data/event-timing.json
- mobile/performance.html
Note that I didn't add the [polyfill](https://github.com/tdresser/input-latency-web-perf-polyfill/tree/gh-pages), since it looks very rough for me...
I'll add Chinese translation in a future commit.
> [mobile] Mention Event Timing Web Perf API

- data/webrtc-relay.json
- data/webrtc-stats.json
- mobile/performance.html
Fix #279.
The `chromestatus` is for `getStats`, which is defined in the webrtc-pc spec. However, the webrtc-stats spec defines the objects returned by `getStats`, so I think it's probably fine to use the `chromestatus` id.
This PR also fixes a URL in `data/webrtc-relay.json`.
(Chinese translation will be made in a future commit.)
> [mobile] Mention Identifiers for WebRTC's Statistics API

- mobile/performance.html
Fix #297. `data-feature-id` was used instead of `data-featureid`.
> [Mobile] Fix reference to CSS contain property

- data/css-overscroll-behavior.json
- mobile/performance.html
The `overscroll-behavior` property is useful e.g. to implement pull-to-refresh and infinite scrolling efficiently. Mentioned in Performance and tuning.
Note the draft is still undergoing transition from the WICG to the CSS WG. The URL of the spec may need to be updated when that transition is complete (and the mention may need to be moved out of the "Exploratory work" section).
Fix #258.
> [Mobile] Mention overscroll-behavior

- data/ttml-imsc1.json
- media/rendering.html
To address issues raised in #283:
- the URL of the IMSC1 spec was updated to target the 1.0.1 Rec.
- TTML2 was moved from "Exploratory work" to "Specification in progress"
- IMSC1.1 gets mentioned in relation with TTML2.
The page lists the 3rd edition of TTML1 already, which seems fine.
> [Media] Update TTWG deliverables in rendering page

- data/element-queries.json
- data/event-timing.json
- data/fetch.json
- data/fullscreen.json
- data/mse-v2.json
- data/permissions-request.json
- data/permissions-revoke.json
- data/priority-hints.json
- data/storage.json
- data/streams.json
- data/xhr.json
- tools/extract-spec-data.js
The spec info generation tool did not properly populate the `deliveredBy` property from the publisher info. It either failed to do so, or actually populated the property with the publisher's info even though the publisher was not a group (e.g. OGC is not a group, it's a consortium made of groups).
See https://github.com/w3c/web-roadmaps/pull/342#pullrequestreview-183114990
> Generate group info automatically from publisher when possible

- data/badging.json
- mobile/lifecycle.html
- mobile/userinput.html
Spec mentioned both in Application lifecycle as part of packaging, and in User interaction as part of the discussion on notifications.
Fix #326
> [Mobile] Mention Badging API

- data/packaging.json
- data/spatial-navigation.json
- tools/extract-spec-data.js
Early proposals in WICG may have an explainer published on `github.com/WICG/`
but no draft spec published on `wicg.github.io`. The code now correctly
associates explainer URLs with WICG.
Fix #348.
> [Framework] Associate "github.com/WICG/" URLs with WICG

- data/writable-files.json
- mobile/storage.html
The File API and Writable Files specifications are probably not the ones that have the strongest impact on mobile, but they should remain useful there too, and the roadmap already mentioned the File API.
The description of the File API now provides more context, and refers to Writable Files for the read-write API.
Fix #324
> [Mobile] Mention Writable Files

- data/frame-timing.json
> [data] Update URL for Frame Timing

- data/css-page-3.json
- data/user-timing.json
- data/webauthn.json
- publishing/CSS.html
A few specs have switched to versioning, with the canonical /TR/ URL now being an alias for a real shortname with a version. The W3C API does not return anything about aliases, so we need to track the versioned URL.
> [Data] Refresh spec URLs

- data/clipboard-apis.json
- mobile/forms.html
The update creates a "Technologies in progress" section in the "Forms" page to mention the specification. Given that the spec is about optimizing user input, this seems a better choice than the "User interaction" page, which is about device-spcific interaction mechanisms.
Fixes #375.
> [Mobile] Mention Clipboard API and Events

- mobile/security.html
The specification has been retired by the Tracking Protection Working Group
in January 2019 due to lack to deployments.
> [mobile] Move DNT to discontinued feature

- data/picture-in-picture.json
Implementation info provided by Can I Use is misleading for Picture-in-Picture
because it gives information about proprietary APIs and equivalent features at
the chrome level across browsers, which do not implement the actual spec for
now.
> [mobile] Fix implementation info for Picture-in-Picture

- mobile/sensors.html
Although still in CR, the specification appears in the well-deployed section of
the Media page already, so we should be consistent across pages.
> [mobile] Move Media Capture and Streams to well-deployed in sensors

- mobile/about.html
- mobile/about.zh.html
- mobile/security.html
- mobile/security.zh.html
Spec not yet supported in Safari but it is supported elsewhere and it has been published as a W3C Recommendation early March.
@xfq Text slightly updated to drop "aims to" in "aims to standardize".
> [mobile] Move Web Authentication to well-deployed technologies

- data/webxr.json
- package.json
Implementation status was for previous WebVR spec. New implementation status
is more aligned with the WebXR spec.
Also update browser-compat-data version in package.json to retrieve the latest
0.0.x version (latest version was not used otherwise)
> [data] Update implementation status for WebXR

- data/webgpu.json
- mobile/graphics.html
Mentions of WebGL and WebGPU were in a note and did not trigger the creation of entries in the implementation table. The text in Well-deployed technologies now properly references the WebGL spec and makes it clear that the implementation info is for version 1.0. It also links to the Exploratory work section that now links to the WebGPU draft.
Note I didn't add a second entry point for WebGL version 2.0 for now, that does not seem necessary.
> [mobile] Properly mention WebGL and WebGPU in Graphics

- media/toc.json
In a recent commit, the "Media application development" page was renamed into "Device interoperability". However, the table of contents file that describes the menu on the home page had not been updated, meaning the page still appeared as "Media application development" there.
This update fixes the issue.
> [media] Update interoperability page title and description in TOC

- media/rendering.html
- media/toc.json
Sets the new `createFeatureSections` flag to have the framework generate feature sections to visually group paragraphs that talk about a same overall feature under a section heading. See:
https://github.com/w3c/web-roadmaps#creating-feature-sections
Except for the first paragraph in the "Rendering" page, all pages that compose the roadmap already had `data-feature` attributes in `<div>` or `<p>` elements, so no need to update the actual contents to take advantage of the flag.
@chrisn, see rationale in https://github.com/w3c/web-roadmaps/pull/450 and https://w3c.github.io/web-roadmaps/mobile/graphics.html for a live example. I believe it makes pages more readable, but that's certainly open for debate. What about it?
> [media] Enable features sections

- data/video-rvfc.json
- media/processing.html
The proposal is now being incubated in the WICG. Also note the change of name (it used to be "video.requestAnimationFrame").
@chrisn, for info.
> [Media] Update pointer to requestVideoFrameCallback() proposal

- data/colorweb.json
- media/rendering.html
- mobile/media.html
This adds the High Dynamic Range / Wide Color Gamut gap analysis document to the Exploratory section, and drops color management from "features not supported by ongoing work".
See #459.
@cpn, for review.
> [media] [mobile] Add HDR/WCG gap analysis doc

- mobile/adaptation.zh.html
- mobile/forms.zh.html
- mobile/graphics.zh.html
- mobile/lifecycle.zh.html
- mobile/media.zh.html
- mobile/network.zh.html
- mobile/payment.zh.html
- mobile/performance.zh.html
- mobile/security.zh.html
- mobile/sensors.zh.html
- mobile/storage.zh.html
- mobile/userinput.zh.html
It would be better if these ids can be automatically generated, but before that happens, I would like to add these more semantic ids (comparing with the ones generated by [generate-utils.js](https://github.com/w3c/web-roadmaps/blob/670fa5758a1d5803e6bf54bf54bd346f68f29600/js/generate-utils.js#L55)) to the Chinese translation.
> Add more ids for the Chinese translation

- data/storage-access.json
- data/storage-buckets.json
- mobile/storage.html
- Move Storage to specifications in progress (fix #485). Not going to well-deployed given lack of support in Safari
- Mention Storage Buckets (fix #493)
- Mention the Storage Access API (developed in Privacy CG, see #492)
> [Mobile] Update Data Storage page

- mobile/security.html
The update also drops mentions of the Interest Groups.
Fix #460.
> [Mobile] Mention guidelines docs in Security and Privacy

- data/mse.json
- data/webaudio.json
- tools/extract-impl-data.js
Properties are no longer maintained in Chrome Platform Status once a feature has shipped. This update makes the code ignore the `prefixed` and `flag` properties when the Chrome Platform Status entry reports that the feature is "Enabled by default".
This means that the code will no longer think that Chrome only has experimental and prefixed support for the Web Audio API and MSE.
See https://github.com/GoogleChrome/chromium-dashboard/issues/1006
Also fixes #427 for good. No further need to hardcode the implementation status for the Web Audio API.
> Chrome Platform Status: ignore prefixed/flag once shipped

- data/web-transport.json
- mobile/network.html
- mobile/network.zh.html
The WebTransport Working Group was created this week to standardize the WebTransport API. The spec has not yet migrated out of WICG, but that should happen soon.
> [Mobile] Move WebTransport to spec in progress

- data/first-party-sets.json
- data/is-logged-in.json
- data/js-membranes.json
- data/private-click-measurement.json
- data/sparrow.json
- data/trust-token-api.json
- data/turtledove.json
- mobile/security.html
- tools/extract-impl-data.js
This updates the security and privacy page to mention the plan to drop third-party cookies and ongoing explorations in the Privacy CG and in the WICG find replacements and to strengthen privacy on the Web.
The update also accounts for the "Harmful" status reported by Chrome Platform Status for the implementation status of "First-party Sets" in Firefox.
Fixes #492.
> [Mobile] Add new privacy explorations

- js/template-about.html
- js/template-about.zh.html
- mobile/about.html
Should we mention the implementation status changes in Edge? There are many, many, changes to the implementation status of Edge in this update because of the EdgeHTML/Chakra->Blink/V8 switch, so listing them one by one may be too long. Perhaps we just need to summarize it in one sentence?
I'll add the Chinese translation after this PR is merged.
(I also moved Edge from "Main browser engines" to "Based on the main browser engines".)
> [mobile] Add changelog for September 2020 release

- js/generate-utils.js
- js/template-groups.zh.html
- mobile/about.html
- mobile/groups.html
- mobile/groups.zh.html
This update creates a new groups page, which appears in the overall menu, that provides a groups' perspective on features mentioned throughout the roadmap.
This gives people who are wondering what particular groups are working on a good overview of features of interest that these groups develop.
Not that this does not add a link on the home page. The groups page remains a bit hidden in the side menu. That's mostly on purpose, the page should be more useful for "advanced" readers, and is less human-friendly since
@xfq Sorry for the last-minute addition. Just realized that we could enable that feature for the mobile roadmap as well. For info, that feature was requested by media folks, and enabled in the media version of the roadmap: https://w3c.github.io/web-roadmaps/media/groups.html. I …
> [Mobile] Add new page to list features mentioned per group

- tools/extract-spec-data.js
These new statuses were introduced in Process 2020.
I note that we may want to highlight CR drafts and snapshots differently in the future. Not done here!
> Support new CR Draft and Snapshot statuses

- .travis.yml
- package.json
For some reason, Travis CI does not seem to obey the `^` prefix and at least fails to load the latest version of browser-specs.
> Bump versions of dependencies
